services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/app
    environment:
      INTERNAL_BACKEND_BASE_URL: ${INTERNAL_BACKEND_BASE_URL}
      NEXT_PUBLIC_FILES_PROTOCOL: ${NEXT_PUBLIC_FILES_PROTOCOL}
      NEXT_PUBLIC_FILES_HOST: ${NEXT_PUBLIC_FILES_HOST}
    command: >
      sh -c "npm install; npm run dev -- --hostname \"0.0.0.0\" --port 3000"
