services:
  frontend:
    image: ${FRONTEND_IMAGE}
    networks:
      - frontend
      - app
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.30"
          memory: 200M
    environment:
      INTERNAL_BACKEND_BASE_URL: ${INTERNAL_BACKEND_BASE_URL}
      NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL}
      NEXT_PUBLIC_FILES_PROTOCOL: ${NEXT_PUBLIC_FILES_PROTOCOL}
      NEXT_PUBLIC_FILES_HOST: ${NEXT_PUBLIC_FILES_HOST}

networks:
  frontend:
    name: frontend
    external: true
  app:
    name: app
    external: true
