name: Frontend CI and CD

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: frontend

  HETZNER_SSH_ADDRESS: ${{ secrets.HETZNER_SSH_ADDRESS }}
  HETZNER_SSH_ENDPOINT: ${{ secrets.HETZNER_SSH_USER }}@${{ secrets.HETZNER_SSH_ADDRESS }}

  INTERNAL_BACKEND_BASE_URL: ${{ secrets.INTERNAL_BACKEND_BASE_URL }}
  NEXT_PUBLIC_BACKEND_BASE_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_BASE_URL }}
  NEXT_PUBLIC_FILES_PROTOCOL: https
  NEXT_PUBLIC_FILES_HOST: ${{ secrets.NEXT_PUBLIC_FILES_HOST }}

jobs:
  ci:
    runs-on: blacksmith-8vcpu-ubuntu-2404

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build image
        uses: ./.github/actions/docker-build
        with:
          context: .
          dockerfile: Dockerfile
          image-name: ${{ env.IMAGE_NAME }}
          target: production
          push: false
          container-registry: ${{ env.REGISTRY }}

  build-and-push-images:
    runs-on: blacksmith-8vcpu-ubuntu-2404

    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}

    permissions:
      packages: write
      contents: read

    needs:
      - ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and push image
        uses: ./.github/actions/docker-build
        with:
          context: .
          dockerfile: Dockerfile
          image-name: ${{ env.IMAGE_NAME }}
          target: production
          push: true
          container-registry: ${{ env.REGISTRY }}
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}

    needs:
      - build-and-push-images

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy services
        run: |
          # Setup ssh key
          echo '${{ secrets.HETZNER_SSH_PRIVATE_KEY }}' > ~/hetzner-key.pem
          chmod 400 ~/hetzner-key.pem

          mkdir -p ~/.ssh
          ssh-keyscan -H $HETZNER_SSH_ADDRESS >> ~/.ssh/known_hosts 2>/dev/null

          # Ensure remote directory exists
          ssh -q -i ~/hetzner-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $HETZNER_SSH_ENDPOINT << 'EOF' >/dev/null 2>&1
            mkdir -p /tmp/deployment_frontend
            chown ${{ secrets.HETZNER_SSH_USER }}:${{ secrets.HETZNER_SSH_USER }} /tmp/deployment_frontend

          EOF

          # Copy files
          scp -q -i ~/hetzner-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./compose.frontend.yaml $HETZNER_SSH_ENDPOINT:/tmp/deployment_frontend/ 2>/dev/null

          # Connect and deploy services
          ssh -q -i ~/hetzner-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $HETZNER_SSH_ENDPOINT << 'EOF' >/dev/null 2>&1
            echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin > /dev/null 2>&1

            export FRONTEND_IMAGE='${{ secrets.FRONTEND_IMAGE }}'
            export INTERNAL_BACKEND_BASE_URL='${{ env.INTERNAL_BACKEND_BASE_URL }}'
            export NEXT_PUBLIC_BACKEND_BASE_URL='${{ env.NEXT_PUBLIC_BACKEND_BASE_URL }}'
            export NEXT_PUBLIC_FILES_PROTOCOL='${{ env.NEXT_PUBLIC_FILES_PROTOCOL }}'
            export NEXT_PUBLIC_FILES_HOST='${{ env.NEXT_PUBLIC_FILES_HOST }}'

            # Run Docker Compose
            cd /tmp/deployment_frontend/

            docker compose -f compose.frontend.yaml --project-name frontend up --pull always --detach > /dev/null 2>&1

            rm -rf /tmp/deployment_frontend
          EOF
